### ISSUE TITLE
[bug] Can't select custom ambiences

### ISSUE THREAD

**Issue by DylanVanAssche** [kimmoli/onyx-triambience-settings-plugin#1]
I made several ambiences from the gallery but they don't show up in the triambience selector.
I can see them in Ambiences without any issue. Seems Jolla uses a different path for custom created ambiences...

**Comment by kimmoli** [comment]
Known issue. Currently _Triambience_ uses only the system path to look ambiences, DIY ones should be in a database.

**Comment by DylanVanAssche** [comment]
Oh didn't know that :p

**Comment by kimmoli** [comment]
And this db is under privileged access, so "nemo" can't read it

**Comment by DylanVanAssche** [comment]
Oh that's pitty :(

**Comment by kimmoli** [comment]
Well. Learned few days ago that settings stuff runs privileged, so...

https://github.com/kimmoli/onyx-triambience-settings-plugin/pull/2

test build available here https://build.merproject.org/package/show/home:kimmoli/onyx-triambience-settings-plugin

**Comment by DylanVanAssche** [comment]
Great! Thank you!
I guess this will be included in beta-6 or so? First the 2.1 release I guess...
